### ISSUE TITLE
Issue with php 7.3 dll thread safe

### ISSUE THREAD

**Issue by aragonfernando** [ibmdb/php_ibm_db2#10]
I tried to load the php_ibm_db2.dll file for php 7.3 thread safe and an error showed up that was unabled to load this dynamic library. It worked for php 7.2 thread safe the respective file, but I couldn't make it work for this version

**Comment by robsonpiere** [comment]
Are you using apache with mod_php?

Did you put the driver in PATH?

**Comment by aragonfernando** [comment]
I used xampp with php 7.2.31 I added the dll file in php/ext folder (the one in extension_dir) and added the extension= in different formats first as php_ibm_db2.dll , next as php_ibm_db2 and last as ibm_db2 and got the same error

**Comment by robsonpiere** [comment]
These are the steps I take:

1. download the odbc driver from the ibm website: https://www.ibm.com/support/pages/node/323035 I'm using version 11.1

2. install the odbc driver and add the bin folder to the Windows PATH https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/t0023866.html

3.  Restart (if you use apache with mod_php)

4. in php.ini add `extension=ibm_db2`

worked on apache and iis.

**Comment by praveen-db2** [comment]
closing this issue as its inactive from long time and hoping its resolved at user end.
