### ISSUE TITLE
Unable to load dynamic library

### ISSUE THREAD

**Issue by andreescocard** [ibmdb/php_ibm_db2#11]
Using PHP Version 5.6.40 in Xampp
Tried many things, none of them worked
Downloaded the .dll file to ext folder, added extension=php_ibm_db2.dll to php.ini and restarted apache > no success
Downloaded IBM Data Server Driver Package, added bin folder to PATH > no success
I'm on Windows 10, anyone configured successfully on it?
Thanks

**Comment by Jelbert** [comment]
I have the same problem.

**Comment by praveen-db2** [comment]
we are already at PHP 8.0 hence closing this.
