### ISSUE TITLE
Dll for 1.4.1 and PHP 8 🐘

### ISSUE THREAD

**Issue by robsonpiere** [ibmdb/php_ibm_db2#12]
Version [ PDO 1.4.1 ](https://github.com/php/pecl-database-pdo_ibm/releases)has been released.  
[PHP 8](https://www.php.net/releases/8.0/en.php) was launched. :tada:

- Could you build the dll's for php 7.4 x64 ts and nts?
- Could you build the dll's for php 8  x64 ts and nts?

**Comment by praveen-db2** [comment]
Closing this as its addresed.
