### ISSUE TITLE
Suggestion: show the release tags corresponding to each prebuilt DLL on ibmdb/php_ibm_db2

### ISSUE THREAD

**Issue by imavo** [ibmdb/php_ibm_db2#13]
When you make the pre-built DLL files for php_ibm_db2.dll  and php_pdo_ibm.dll  available on the repository at
https://github.com/ibmdb/php_ibm_db2  
,  it would be helpful if you also specified the ibm_db2 (and pdo_ibm) release tag(s) corresponding to the build. 

This will make it easier for people to know the starting point release if they want to build the pecl extensions from source code on Microsoft Windows for whatever reason. I know it's possible to work it out from dates, but would'nt be better to avoid doubt and just specify the corresponding source release tags?

**Comment by praveen-db2** [comment]
@imavo from next release we will work on this, thanks for your suggestion. Can you close this ?
