### ISSUE TITLE
Unable to build php ds driver from source

### ISSUE THREAD

**Issue by Anshu-Garg** [ibmdb/php_ibm_db2#15]
Platform Power
OS: AIX 7.1

Target Db2 : 11.5.7

php: 8.1.4

Error

# pwd
/php64/php-8.1.4
**# ./configure --prefix=/php64/php-8.1.4 --enable-cli --enable-pdo --without-sqlite3 --without-pdo-sqlite**                 
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... powerpc-ibm-aix7.1.5.0
checking host system type... powerpc-ibm-aix7.1.5.0
checking target system type... powerpc-ibm-aix7.1.5.0
checking for pkg-config... no
checking for cc... no
checking for gcc... no
configure: error: in `/php64/php-8.1.4':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
# ls
.appveyor.yml        .gitattributes       CODING_STANDARDS.md  Makefile.fragments   README.md            Zend                 build                config.nice          ext                  pear                 sapi                 win32
.cirrus.yml          .github              CONTRIBUTING.md      Makefile.objects     TSRM                 appveyor             buildconf            configure            include              php.ini-development  scripts
.editorconfig        .gitignore           EXTENSIONS           NEWS                 UPGRADING            azure                buildconf.bat        configure.ac         libs                 php.ini-production   tests
.gdbinit             .travis.yml          LICENSE              README.REDIST.BINS   UPGRADING.INTERNALS  azure-pipelines.yml  config.log           docs                 main                 run-tests.php        travis
# vi config.log
# vi config.log
# php --version
ksh: php:  not found.
# ls
.appveyor.yml        .gitattributes       CODING_STANDARDS.md  Makefile.fragments   README.md            Zend                 build                config.nice          ext                  pear                 sapi                 win32
.cirrus.yml          .github              CONTRIBUTING.md      Makefile.objects     TSRM                 appveyor             buildconf            configure            include              php.ini-development  scripts
.editorconfig        .gitignore           EXTENSIONS           NEWS                 UPGRADING            azure                buildconf.bat        configure.ac         libs                 php.ini-production   tests
.gdbinit             .travis.yml          LICENSE              README.REDIST.BINS   UPGRADING.INTERNALS  azure-pipelines.yml  config.log           docs                 main                 run-tests.php        travis
# pwd
/php64/php-8.1.4
# ls
.appveyor.yml        .gitattributes       CODING_STANDARDS.md  Makefile.fragments   README.md            Zend                 build                config.nice          ext                  pear                 sapi                 win32
.cirrus.yml          .github              CONTRIBUTING.md      Makefile.objects     TSRM                 appveyor             buildconf            configure            include              php.ini-development  scripts
.editorconfig        .gitignore           EXTENSIONS           NEWS                 UPGRADING            azure                buildconf.bat        configure.ac         libs                 php.ini-production   tests
.gdbinit             .travis.yml          LICENSE              README.REDIST.BINS   UPGRADING.INTERNALS  azure-pipelines.yml  config.log           docs                 main                 run-tests.php        travis
**# ./configure --prefix=/php64/php814 --enable-cli --enable-pdo --without-sqlite3 --without-pdo-sqlite**                 
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... powerpc-ibm-aix7.1.5.0
checking host system type... powerpc-ibm-aix7.1.5.0
checking target system type... powerpc-ibm-aix7.1.5.0
checking for pkg-config... no
checking for cc... no
checking for gcc... no
configure: error: in `/php64/php-8.1.4':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
# pwd
/php64/php-8.1.4
#

**Comment by praveen-db2** [comment]
@Anshu-Garg were you able to resolve this ? can we close this ?
