### ISSUE TITLE
.dll for PHP 8.1

### ISSUE THREAD

**Issue by Marshal-Brummel** [ibmdb/php_ibm_db2#16]
Could you build the dll's for php 8.1?

**Comment by praveen-db2** [comment]
@Hangry9090 we are in between some other priorities, will take this up later. Atleast I cannot assure we can do it in another 1 or 2 months, If we are lucky it might happen before that as well.

**Comment by Marshal-Brummel** [comment]
Do you have an updated estimate for these dll's at the moment?

**Comment by praveen-db2** [comment]
@Hangry9090 Will check with my lead once and see if we can work on this at earliest

**Comment by praveen-db2** [comment]
@Hangry9090 we plan to take this up in coming sprint if no other high priorities work comes.

**Comment by praveen-db2** [comment]
@Hangry9090 DLLs for PHP 8.1 are released. Hence closing this issue. You are free to reopen if you find any issues.
