### ISSUE TITLE
cannot load dinamic library

### ISSUE THREAD

**Issue by faisalishak** [ibmdb/php_ibm_db2#2]
hello mister can you help me, about this error ?

PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_ibm_db2.dll' - The specified module could not be found.
 in Unknown on line 0

I'm using PHP 7.1.10

when I paste DLL to xampp/php/ext folder and add extendtion=php_ibm_db2.dll at  php.ini

**Comment by abhi7436** [comment]
Hi,
In your environment variable PATH can you set bin directory of your db2 driver and check.

**Comment by faisalishak** [comment]
I Have set PATH to environment variable "Program Files/IBM/Driver Server Package/bin"
but still not work on my machine.

**Comment by abhi7436** [comment]
Hi,
I expect below is typo in defect description if not then please make it as extension=php_ibm_db2.
                           `"extendtion=php_ibm_db2.dll at php.ini"` 

I tested it to my enviroment it is working fine, That makes your environment is no set properly.

Have you downloaded correct dll version for PHP 7.1? 
TS or NTS?
x86 or x64?

Let me know the whether you are using x86 or x64 and TS or NTS?

**Comment by faisalishak** [comment]
Well note, thank you mister. Solve
