### ISSUE TITLE
the dll does not work with xampp (x64) 

### ISSUE THREAD

**Issue by JHONF2078** [ibmdb/php_ibm_db2#5]
the dll does not work with xampp (x64) and php 7.3.4, it is not even shown inside the php modules, with 32 bits there is no problem, the problem is in the dlls by 64 bit (I'm using IBM x64_clientsdk.4.10 .FC7DE.WIN)

**Comment by abhi7436** [comment]
I believe you are using Informix driver( IBM x64_clientsdk.4.10 .FC7DE.WIN). This dlls are generated for IBM Db2 Clidriver. can you try installing clidriver and check.
Pasted below the link to download clidriver.
https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/

**Comment by JHONF2078** [comment]
hello 
compile the pdo_informix dll using php_sdk and work ok.
Thank you
https://github.com/JHONF2078/php-dll-para-windows
