### ISSUE TITLE
Unable to load dynamic library - (The specified module could not be found.)) in Unknown on line 0

### ISSUE THREAD

**Issue by mblandgithub** [ibmdb/php_ibm_db2#6]
I have been trying to find the right drivers.  I get this when using ts and nts drivers.

P Warning:  PHP Startup: Unable to load dynamic library 'php_ibm_db2' (tried: D:\\xampp\\php\\ext\\php_ibm_db2 (The specified module could not be found.), D:\\xampp\\php\\ext\\php_php_ibm_db2.dll (The specified module could not be found.)) in Unknown on line 0

php.ini
extension=php_ibm_db2

Downloaded from 
https://github.com/ibmdb/php_ibm_db2/tree/master/PHP%207.3.x/x64

PHP Version 7.3.7
System 	Windows NT CODWIN1 10.0 build 14393 (Windows Server 2016) AMD64
Build Date 	Jul 3 2019 14:26:40
Compiler 	MSVC15 (Visual C++ 2017)
Architecture 	x64
Configure Command 	cscript /nologo configure.js "--enable-snapshot-build" "--enable-debug-pack" "--with-pdo-oci=c:\php-snap-build\deps_aux\oracle\x64\instantclient_12_1\sdk,shared" "--with-oci8-12c=c:\php-snap-build\deps_aux\oracle\x64\instantclient_12_1\sdk,shared" "--enable-object-out-dir=../obj/" "--enable-com-dotnet=shared" "--without-analyzer" "--with-pgo"
Server API 	Apache 2.0 Handler
Virtual Directory Support 	enabled
Configuration File (php.ini) Path 	C:\Windows
Loaded Configuration File 	D:\xampp\php\php.ini
Scan this dir for additional .ini files 	(none)
Additional .ini files parsed 	(none)
PHP API 	20180731
PHP Extension 	20180731
Zend Extension 	320180731
Zend Extension Build 	API320180731,TS,VC15
PHP Extension Build 	API20180731,TS,VC15
Debug Build 	no
Thread Safety 	enabled
Thread API 	Windows Threads
Zend Signal Handling 	disabled
Zend Memory Manager 	enabled
Zend Multibyte Support 	provided by mbstring
IPv6 Support 	enabled
DTrace Support 	disabled
Registered PHP Streams	php, file, glob, data, http, ftp, zip, compress.zlib, compress.bzip2, https, ftps, phar
Registered Stream Socket Transports	tcp, udp, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, zlib.*, bzip2.*
Zend logo This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
Configuration
apache2handler
Apache Version 	Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.3.7
Apache API Version 	20120211
Server Administrator 	postmaster@localhost
Hostname:Port 	localhost:80
Max Requests 	Per Child: 0 - Keep Alive: on - Max Per Connection: 100
Timeouts 	Connection: 300 - Keep-Alive: 5
Virtual Server 	No
Server Root 	D:/xampp/apache

**Comment by mblandgithub** [comment]
I must have done something b/c now it works.

**Comment by edgarguzman** [comment]
Hello, did you manage to solve the problem? I have the same problem.

**Comment by edgarguzman** [comment]
> I must have done something b/c now it works.

Hello, did you manage to solve the problem? I have the same problem.
